"""Genesis simulation environment for the do-as-i-do reproduction."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import genesis as gs
import numpy as np

from .assets import ensure_bimanual_robot
from .data import DemoSequence, RobotTrajectory
from .retargeting import UR3_ARM_JOINTS, _flatten_indices, _hand_joint_names, get_joint


class DoAsIDoEnv:
    """Bimanual manipulation environment for replaying retargeted demos.

    The robot is a merged dual-UR3 + dual-Allegro URDF generated by
    ``core.assets.ensure_bimanual_robot``.  The environment supports
    headless/viewer modes and camera rendering.
    """

    def __init__(
        self,
        config: Optional[dict[str, Any]] = None,
        headless: bool = True,
    ) -> None:
        self.config = config or {}
        self.headless = self.config.get("headless", headless)
        self.dt = float(self.config.get("simulation", {}).get("dt", 0.01))
        self.substeps = int(self.config.get("simulation", {}).get("substeps", 10))
        self.table_height = float(self.config.get("scene", {}).get("table_height", 0.75))
        self.table_size = tuple(self.config.get("scene", {}).get("table_size", [0.8, 1.2, 0.02]))
        self.object_size = float(self.config.get("scene", {}).get("object_size", 0.05))
        self.object_density = float(self.config.get("scene", {}).get("object_density", 500.0))

        if not gs._initialized:
            backend = self.config.get("simulation", {}).get("backend", "cpu")
            gs.init(backend=getattr(gs, backend, gs.cpu))

        self.scene = self._build_scene()
        self.robot = self._load_robot()
        self.table = self._build_table()
        self.object_entity = self._build_object()
        self.camera = self._build_camera()

        self.scene.build()

        self._q0 = self.robot.get_qpos().cpu().numpy().flatten().copy()
        self._build_dof_indices()
        self.n_dofs = self.robot.n_dofs
        self.action_dim = self.n_dofs
        self.obs_dim = self.n_dofs * 2 + 3 + 4 + 3  # qpos + qvel + obj pos/quat + target pos

        self.current_step = 0
        self.max_steps = int(self.config.get("env", {}).get("max_steps", 500))

    def _build_scene(self) -> gs.Scene:
        return gs.Scene(
            viewer_options=gs.options.ViewerOptions(
                camera_pos=(1.2, 0.0, 1.0),
                camera_lookat=(0.0, 0.0, 0.5),
                camera_fov=50,
            ) if not self.headless else None,
            sim_options=gs.options.SimOptions(
                dt=self.dt,
                substeps=self.substeps,
            ),
            show_viewer=not self.headless,
        )

    def _load_robot(self) -> Any:
        urdf_path = self.config.get("robot", {}).get("urdf_path")
        if urdf_path is None:
            hand_type = self.config.get("robot", {}).get("hand_type", "allegro")
            urdf_path = ensure_bimanual_robot(hand_type=hand_type)
        urdf_path = Path(urdf_path)
        if not urdf_path.exists():
            raise FileNotFoundError(f"Robot URDF not found: {urdf_path}")
        return self.scene.add_entity(
            morph=gs.morphs.URDF(
                file=str(urdf_path),
                fixed=True,
                recompute_inertia=True,
                merge_fixed_links=False,
            ),
        )

    def _build_dof_indices(self) -> None:
        """Cache the DOF indices for each arm/hand so replay is order-agnostic."""
        hand_type = self.config.get("robot", {}).get("hand_type", "allegro")

        def find(side: str, names: list[str]) -> list[int]:
            idxs: list[int] = []
            for name in names:
                joint = get_joint(self.robot, f"{side}_{name}")
                idxs.append(_flatten_indices([joint.dofs_idx_local]))
            return [i for sub in idxs for i in sub]

        self.left_arm_dofs = find("left", UR3_ARM_JOINTS)
        self.right_arm_dofs = find("right", UR3_ARM_JOINTS)
        self.left_hand_dofs = find("left_hand", _hand_joint_names(hand_type))
        self.right_hand_dofs = find("right_hand", _hand_joint_names(hand_type))

    def _build_table(self) -> Any:
        return self.scene.add_entity(
            morph=gs.morphs.Box(
                size=self.table_size,
                pos=(0.0, 0.0, self.table_height - self.table_size[2] / 2),
            ),
            surface=gs.surfaces.Default(color=(0.6, 0.5, 0.4, 1.0)),
        )

    def _build_object(self) -> Any:
        obj_mesh_path = self.config.get("scene", {}).get("object_mesh_path")
        if obj_mesh_path and Path(obj_mesh_path).exists():
            return self.scene.add_entity(
                morph=gs.morphs.Mesh(
                    file=str(obj_mesh_path),
                    scale=1.0,
                    pos=(0.0, 0.0, self.table_height + 0.05),
                ),
                surface=gs.surfaces.Default(color=(0.8, 0.3, 0.2, 1.0)),
            )
        return self.scene.add_entity(
            morph=gs.morphs.Box(
                size=(self.object_size,) * 3,
                pos=(0.0, 0.0, self.table_height + self.object_size / 2),
            ),
            surface=gs.surfaces.Default(color=(0.8, 0.3, 0.2, 1.0)),
        )

    def _build_camera(self) -> Optional[Any]:
        # Do not create a camera in headless mode unless explicitly requested,
        # because it triggers visualizer teardown issues on some headless hosts.
        if self.headless and not self.config.get("cameras", {}).get("enabled", False):
            return None
        return self.scene.add_camera(
            pos=(0.8, 0.0, 1.2),
            lookat=(0.0, 0.0, 0.5),
            fov=50,
            res=(640, 480),
        )

    def _object_target_position(self) -> np.ndarray:
        return np.array([0.15, 0.0, self.table_height + self.object_size / 2], dtype=np.float32)

    def reset(self, seed: int = 0) -> dict[str, np.ndarray]:
        self.current_step = 0
        np.random.seed(seed)
        self.robot.set_qpos(self._q0)
        self.object_entity.set_pos((0.0, 0.0, self.table_height + self.object_size / 2))
        self.object_entity.set_quat((0.0, 0.0, 0.0, 1.0))
        # Stabilize.
        for _ in range(10):
            self.scene.step()
        return self.get_observation()

    def get_observation(self) -> dict[str, np.ndarray]:
        qpos = self.robot.get_qpos().cpu().numpy().flatten().astype(np.float32)
        qvel = self.robot.get_dofs_velocity().cpu().numpy().flatten().astype(np.float32)
        obj_pos = self.object_entity.get_pos().cpu().numpy().flatten().astype(np.float32)
        obj_quat = self.object_entity.get_quat().cpu().numpy().flatten().astype(np.float32)
        target = self._object_target_position()
        proprio = np.concatenate([qpos, qvel, obj_pos, obj_quat, target])
        obs = {"proprioception": proprio}
        if self.camera is not None:
            obs["rgb"] = self.camera.render(rgb=True)[0]
        return obs

    def step(self, action: np.ndarray) -> tuple[dict[str, np.ndarray], float, bool, bool, dict]:
        action = np.asarray(action, dtype=np.float32)
        if len(action) != self.n_dofs:
            raise ValueError(f"Expected action of length {self.n_dofs}, got {len(action)}")
        self.robot.control_dofs_position(action)
        self.scene.step()
        self.current_step += 1

        obs = self.get_observation()
        reward = float(self._compute_reward(obs))
        terminated = self._check_terminated(obs)
        truncated = self.current_step >= self.max_steps
        info = {"step": self.current_step, "success": terminated}
        return obs, reward, terminated, truncated, info

    def _compute_reward(self, obs: dict[str, np.ndarray]) -> float:
        # Simple reward: encourage object to reach target and penalize action magnitude.
        proprio = obs["proprioception"]
        n = self.n_dofs
        obj_pos = proprio[n * 2 : n * 2 + 3]
        target = proprio[n * 2 + 7 : n * 2 + 10]
        obj_to_target = np.linalg.norm(obj_pos - target)
        action_mag = np.linalg.norm(proprio[:n])
        return -obj_to_target - 0.001 * action_mag

    def _check_terminated(self, obs: dict[str, np.ndarray]) -> bool:
        proprio = obs["proprioception"]
        n = self.n_dofs
        obj_pos = proprio[n * 2 : n * 2 + 3]
        target = proprio[n * 2 + 7 : n * 2 + 10]
        return bool(np.linalg.norm(obj_pos - target) < 0.03)

    def replay(
        self,
        trajectory: RobotTrajectory,
        object_trajectory: Optional[Any] = None,
        close_on_finish: bool = False,
    ) -> list[dict[str, np.ndarray]]:
        """Replay a retargeted joint trajectory in simulation.

        Args:
            trajectory: ``RobotTrajectory`` to replay.
            object_trajectory: optional per-frame object pose used to reset the
                object at each frame (for visual alignment).
            close_on_finish: whether to close the environment after replay.
        """
        observations = []
        q = np.zeros(self.n_dofs, dtype=np.float32)
        for i in range(len(trajectory)):
            q[self.left_arm_dofs] = trajectory.left_arm_q[i]
            q[self.right_arm_dofs] = trajectory.right_arm_q[i]
            q[self.left_hand_dofs] = trajectory.left_hand_q[i]
            q[self.right_hand_dofs] = trajectory.right_hand_q[i]
            self.robot.control_dofs_position(q)
            if object_trajectory is not None:
                self.object_entity.set_pos(object_trajectory.positions[i])
                self.object_entity.set_quat(object_trajectory.orientations[i])
            self.scene.step()
            observations.append(self.get_observation())
        if close_on_finish:
            self.close()
        return observations

    def retarget(self, demo: DemoSequence) -> RobotTrajectory:
        """Convenience method to retarget a demo using this env's robot."""
        from .retargeting import build_retargeter

        retargeter = build_retargeter(self.config, self.robot)
        return retargeter.retarget(demo)

    def render(self, rgb: bool = True) -> Optional[np.ndarray]:
        if self.camera is None:
            return None
        return self.camera.render(rgb=rgb)[0]

    def close(self) -> None:
        try:
            gs.destroy()
        except Exception:
            # Visualizer teardown can fail in headless/offscreen contexts; ignore.
            pass
