"""把 ArticulationResult 导出为可加载的 URDF（stdlib，无依赖）。

约定（与估计器输出一致）：

- 所有部件的 mesh/顶点以**世界坐标静止位姿**给出；
- 关节 frame = 原点平移到 ``JointSpec.origin``、姿态与世界系一致
  （rpy = 0），因此 ``axis`` 直接写世界分量即可；
- 子 link 的几何用 ``<origin xyz="部件中心 - 关节原点">`` 补偿；
- base link 固定（``<joint type="fixed">`` 到 world 可选，这里省略，
  Genesis / MuJoCo / PyBullet 均允许单一根 link）。

若部件提供 ``mesh_path``，visual 引用该 mesh（假定 mesh 文件本身已是
世界坐标静止位姿）；collision 始终用包裹盒，保证物理加载不需要
convex decomposition。
"""

from __future__ import annotations

from xml.etree import ElementTree as ET
from xml.sax.saxutils import escape

import numpy as np

from .joint_spec import ArticulatedPart, ArticulationResult, JointType

_URDF_TEMPLATE = """<?xml version="1.0"?>
<!-- Auto-generated by articulation_gen. 部件均为世界坐标静止位姿。 -->
<robot name="{name}">
{body}
</robot>
"""


def _fmt(values: tuple[float, ...] | list[float] | np.ndarray) -> str:
    return " ".join(f"{float(v):.6g}" for v in values)


def _aabb(vertices: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mn, mx = vertices.min(axis=0), vertices.max(axis=0)
    return (mn + mx) / 2.0, mx - mn


def _inertial_block(mass: float, size: np.ndarray, indent: str) -> str:
    x, y, z = (float(v) for v in size)
    ixx = mass / 12.0 * (y * y + z * z)
    iyy = mass / 12.0 * (x * x + z * z)
    izz = mass / 12.0 * (x * x + y * y)
    return (
        f"{indent}<inertial>\n"
        f'{indent}  <origin xyz="0 0 0" rpy="0 0 0"/>\n'
        f'{indent}  <mass value="{mass:.6g}"/>\n'
        f'{indent}  <inertia ixx="{ixx:.6g}" ixy="0" ixz="0" '
        f'iyy="{iyy:.6g}" iyz="0" izz="{izz:.6g}"/>\n'
        f"{indent}</inertial>\n"
    )


def _link_block(
    part: ArticulatedPart,
    *,
    frame_origin: np.ndarray,
    mass: float,
    indent: str,
) -> str:
    """一个 link 的 URDF 片段；frame_origin 为该 link 系原点的世界坐标。"""
    center_world, size = _aabb(part.vertices)
    rel = center_world - frame_origin
    lines = [f'{indent}<link name="{escape(part.name)}">\n']
    lines.append(_inertial_block(mass, size, indent))
    visual_origin = f'<origin xyz="{_fmt(rel)}" rpy="0 0 0"/>'
    if part.mesh_path:
        lines.append(
            f"{indent}  <visual>\n"
            f"    {indent}{visual_origin}\n"
            f'    {indent}<geometry><mesh filename="{escape(part.mesh_path)}"/></geometry>\n'
            f"{indent}  </visual>\n"
        )
    else:
        lines.append(
            f"{indent}  <visual>\n"
            f"    {indent}{visual_origin}\n"
            f'    {indent}<geometry><box size="{_fmt(size)}"/></geometry>\n'
            f"{indent}  </visual>\n"
        )
    lines.append(
        f"{indent}  <collision>\n"
        f'    {indent}<origin xyz="{_fmt(rel)}" rpy="0 0 0"/>\n'
        f'    {indent}<geometry><box size="{_fmt(size)}"/></geometry>\n'
        f"{indent}  </collision>\n"
    )
    lines.append(f"{indent}</link>\n")
    return "".join(lines)


def result_to_urdf(
    result: ArticulationResult,
    parts: list[ArticulatedPart],
    *,
    object_name: str = "articulated_object",
    link_mass: float = 1.0,
) -> str:
    """生成 URDF 字符串。

    Args:
        result: ``estimate_joints`` 的输出。
        parts: 参与估计的全部部件（含 base）。
        object_name: URDF robot 名。
        link_mass: 每个 link 的占位质量（真实值请按材质体积换算后修正）。
    """
    by_name = {p.name: p for p in parts}
    if result.base not in by_name:
        raise KeyError(f"base part {result.base!r} not in parts")

    body: list[str] = []
    # base：link 系原点 = 世界原点
    body.append(
        _link_block(
            by_name[result.base], frame_origin=np.zeros(3), mass=link_mass, indent="  "
        )
    )

    for joint in result.joints:
        child = by_name.get(joint.child)
        if child is None:
            raise KeyError(f"joint {joint.name!r} child {joint.child!r} not in parts")
        origin = np.asarray(joint.origin, dtype=np.float64)
        limit_attrs = (
            f'lower="{joint.lower:.6g}" upper="{joint.upper:.6g}" '
            'effort="50" velocity="2"'
        )
        body.append(
            f'  <joint name="{escape(joint.name)}" type="{joint.joint_type.value}">\n'
            f'    <parent link="{escape(joint.parent)}"/>\n'
            f'    <child link="{escape(joint.child)}"/>\n'
            f'    <origin xyz="{_fmt(origin)}" rpy="0 0 0"/>\n'
            f'    <axis xyz="{_fmt(joint.axis)}"/>\n'
            f"    <limit {limit_attrs}/>\n"
            f"  </joint>\n"
        )
        body.append(
            _link_block(child, frame_origin=origin, mass=link_mass, indent="  ")
        )

    return _URDF_TEMPLATE.format(name=escape(object_name), body="".join(body))


def validate_urdf(urdf_text: str) -> ET.Element:
    """解析校验（结构良好 + 基本引用完整），返回根 Element。"""
    root = ET.fromstring(urdf_text)
    if root.tag != "robot":
        raise ValueError(f"root element must be <robot>, got <{root.tag}>")
    links = {el.get("name") for el in root.findall("link")}
    if not links:
        raise ValueError("URDF has no <link>")
    for joint in root.findall("joint"):
        jtype = joint.get("type")
        if jtype not in {t.value for t in JointType} | {"fixed"}:
            raise ValueError(f"unsupported joint type {jtype!r}")
        parent = joint.find("parent")
        child = joint.find("child")
        if parent is None or child is None:
            raise ValueError(f"joint {joint.get('name')!r} missing parent/child")
        if parent.get("link") not in links or child.get("link") not in links:
            raise ValueError(f"joint {joint.get('name')!r} references unknown link")
    return root


__all__ = ["result_to_urdf", "validate_urdf"]
